<a href="https://colab.research.google.com/github/stha1122/Machine_Learning_with_Python/blob/main/TensorFlow_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensors**

"A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes." (https://www.tensorflow.org/guide/tensor)

It should't surprise you that tensors are a fundemental apsect of TensorFlow. They are the main objects that are passed around and manipluated throughout the program. Each tensor represents a partialy defined computation that will eventually produce a value. TensorFlow programs work by building a graph of Tensor objects that details how tensors are related. Running different parts of the graph allow results to be generated.

Each tensor has a data type and a shape.

**Data Types Include**: float32, int32, string and others.

Shape: Represents the dimension of data.

Just like vectors and matrices tensors can have operations applied to them like addition, subtraction, dot product, cross product etc.

In the next sections we will discuss some different properties of tensors. This is to make you more familiar with how tensorflow represnts data and how you can manipulate this data.

Below is an example of how to create some different *tensors*

In [2]:
import tensorflow as tf

In [3]:
string = tf.Variable("this is a string",tf.string)
number = tf.Variable(324,tf.int16)
floating = tf.Variable(3.567,tf.float64)

## **Rank/Degree of Tensors**

Another word for rank is degree,these terms simply mean the number of dimensions invovled in the tensor.What we created above is a tensor of rank 0,also known as a scalar.

Now we'll create some tensors of higher degrees/ranks.

In [19]:
rank1_tensor = tf.Variable(["Test","ok","learn"],tf.string)
rank2_tensor = tf.Variable([["test","ok","ko"],["test","yes","ko"]],tf.string)

To **determine the rank** of tensor we can call the following method.

In [20]:
print(tf.rank(number))
print(tf.rank(rank1_tensor))
print(tf.rank(rank2_tensor))

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


## **Shape of Tensors**

Now that we've seen about the rank of tensors it's time to talk about the shape.The shape of a tensor is simply the amount of elements that exist in each dimension.TensorFlow will try to determine the shape of tensor but sometimes it may be unkonwn.

To **get the shape** of a tensor we use the shape attribute.

In [21]:
print(number.shape)
print(rank1_tensor.shape)
print(rank2_tensor.shape)

()
(3,)
(2, 3)


## **Change Shape**
The number of elements of a tensor is the product of the sizes of all its shapes.There are often many shapes that have the same number of elements,making it convient to be able to change the shape of a tensor.

The example below shows how to change the shape of a tensor.

In [22]:
tensor1 = tf.ones([1,2,3]) #tf.ones() creates a shape [1,2,3] tensor full of ones.
tensor2 = tf.reshape(tensor1,[2,3,1]) # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3,-1]) # -1 tells the tensor to calculate the size of the dimension in that place
                                      # this will reshape the tensor to [3,2]

# The number of elemnts in the reshaped tensor MUST match the number in the original


Now let's have a look at our different tensors

In [23]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


## Types of tensors
There are different types of tensors.These are the most commonly used.



*   Variable
*   Constant
*   Placeholder
*   SparseTensor

With the execption of Variable all of these tensors are immuttable,meaning their value may not change during execution.





## **Evaluating Tensors**
Evaluating the Tensors in other words ,get its value.Since tensors represent a partially complete computation we will sometimes need to run what's called a session to evaluate the tensor.

There are many diiferent ways to achieve this but I will note the simplest way


In [25]:
# with tf.Session() as sess: # creates a session using the default graph
#   tensor.eval()            # tensor will be name of tensor